name = "kpop-comebacks"
main = "worker.js"
compatibility_date = "2023-02-28"
workers_dev = false
minify = true

kv_namespaces = [
  { binding = "data", id = "2742623002b041759dd02d62e0a6688d", preview_id = "ebd975bc248d4f14a86f80b5a362b92f" }
]

rules = [
  { type = "Text", globs = ["**/**.js.txt"], fallthrough = true },
  { type = "Text", globs = ["**/*.css"], fallthrough = true },
]
