name = "kpop-releases"
main = "worker.js"
compatibility_date = "2023-02-28"

kv_namespaces = [
  { binding = "cache", id = "df76d8aa5ee745809d32e650d0195f42", preview_id = "2c247a04d8bc4523aee1d53fec4864ba" }
]

rules = [
  { type = "Text", globs = ["**/**.txt"], fallthrough = true },
  { type = "Text", globs = ["**/*.css"], fallthrough = true },
]

[triggers]
crons = ["10 9 * * *"]
